[build]
pre_cmd = ["killall -9 gitea 2>/dev/null || true"] # kill off potential zombie processes from previous runs
cmd = "make --no-print-directory backend"
include_ext = ["go", "tmpl"]
include_dir = ["cmd", "models", "modules", "options", "routers", "services"]
exclude_dir = [
  "models/fixtures",
  "modules/git/tests",
  "modules/migration/file_format_testdata",
]
exclude_regex = ["_test.go$", "_gen.go$"]

main_only = true
