version = 1

test_patterns = [
  "test/**.py",
  "test*.py",
  "*.spec.js"
]
  "migrations/**.py",
]

[[analyzers]]
name = "python"
enabled = true


[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]
enabled = false
