version = 1

test_patterns = [
  "*.spec.js"
]
  "migrations/**.py",
]

[[analyzers]]
name = "python"
enabled = true


name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]
enabled = false
