version = 1

test_patterns = [
  "test/**.py",
  "test*.py",
  "*.spec.js"
]
exclude_patterns = [
  "migrations/**.py",
]

[[analyzers]]
name = "python"
enabled = true

  runtime_version = "2.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

name = "black"
enabled = false
